投稿
LCTT/Articles pull request #14
Opened 2022-04-01 09:04 UTC by Cyberbolt

2022-04-01 09:18 UTC, Cyberbolt commented
您好，这篇文章主要介绍 Flask 进程间通信的一个思路，使用个人开发的 Python Package: CyberDB 。希望能通过，谢谢！

2022-04-01 09:18 UTC, Cyberbolt commented
你好，这篇文章主要介绍 Flask 进程间通信的一个思路，使用个人开发的 Python Package: CyberDB 。希望能通过，谢谢！

2022-04-02 12:47 UTC, wxy requested changes

2022-04-02 12:47 UTC, wxy commented on contributions/20220401 Using CyberDB as Flask's In-memory Database in Production.md
> +前面我们讲述了 CyberDB 的[快速上手](https://www.cyberlight.xyz/static/cyberdb-chn/)，现在我们需要把它带到能发挥其作用的地方，在生产环境中将 CyberDB 作为 Flask 的内存数据库，使用 Gunicorn 运行，并实现多进程间的通信。
因为这是一篇独立投稿，所以此处需要重新组织一下说法。

2022-04-02 12:47 UTC, wxy commented on contributions/20220401 Using CyberDB as Flask's In-memory Database in Production.md
> +前面我们讲述了 CyberDB 的[快速上手](https://www.cyberlight.xyz/static/cyberdb-chn/)，现在我们需要把它带到能发挥其作用的地方，在生产环境中将 CyberDB 作为 Flask 的内存数据库，使用 Gunicorn 运行，并实现多进程间的通信。
建议增加如下内容：
- 给 CyberDB 做个简短介绍：它是什么，它能做什么。

2022-04-02 12:47 UTC, wxy commented on contributions/20220401 Using CyberDB as Flask's In-memory Database in Production.md
> + > 生产环境中我们通常选择 Gunicorn 运行 Flask，有没有一个便捷的方法在 Gunicorn 多进程间通信？由此得到了今天的主角 -- CyberDB，一个基于 Python 字典和列表的内存数据库。
这句简介可以更简洁直接一些。现在的简介，导入了 Gunicorn、Flask 名词，反而影响了对 CyberDB 的介绍。可以考虑用：“CyberDB，一个基于 Python 字典和列表的内存数据库。”
而在文章下面的部分再介绍它的用途。

2022-04-02 12:47 UTC, wxy commented on contributions/20220401 Using CyberDB as Flask's In-memory Database in Production.md
> +文件 requirements.txt
这篇文章是围绕几个文件分别介绍来组织，那建议每个文件都做成小节（`####`）来分节。

2022-04-02 12:47 UTC, wxy commented on contributions/20220401 Using CyberDB as Flask's In-memory Database in Production.md
> +文件 cyberdb_init.py
在介绍每个文件时，可以介绍一下它的用途。比如这个文件应该是初始化数据库的，可以写明一下。

2022-04-02 12:47 UTC, wxy commented on contributions/20220401 Using CyberDB as Flask's In-memory Database in Production.md
> +在项目根目录运行
此处应该是新的一节了。但是感觉比较突兀，gunicorn 的引入没有介绍。

2022-04-03 03:27 UTC, Cyberbolt commented on contributions/20220401 Using CyberDB as Flask's In-memory Database in Production.md
> +在项目根目录运行
你好，很高兴收到文章建议！我按要求修改了文章并更新了 GitHub。感谢！

2022-04-03 14:05 UTC, wxy approved these changes

2022-04-03 14:06 UTC, wxy commented on contributions/20220401 Using CyberDB as Flask's In-memory Database in Production.md
> +在项目根目录运行
很高兴看到您做了认真的修改。我合并了，明天发布它。

2022-04-03 14:06 UTC, merged