new article by dongdigua
LCTT/Articles pull request #20
Opened 2022-05-28 12:15 UTC by dongdigua

2022-06-18 08:13 UTC, wxy commented
非常辛苦，我马上去做审阅——抱歉的是我太久没看这个仓库了。

2022-06-18 08:25 UTC, dongdigua commented
我一个月前写的, 现在看来我写的太屑了

2022-06-18 08:37 UTC, wxy requested changes

2022-06-18 08:37 UTC, wxy commented on contributions/20220529 Write a p2p Chat Program in Elixir.md
> +> 尝试用 elixir 写一个 p2p 加密聊天软件
这里可以用简单的一句话来介绍一下 elixir 是什么，以免不了解的同学缺乏概念。

2022-06-18 08:37 UTC, wxy commented on contributions/20220529 Write a p2p Chat Program in Elixir.md
> +- UDP 打洞<br>
这里你使用 `<br>` 来做换行，其实不符合 Markdown 惯例。请用两个回车来换行。

2022-06-18 08:37 UTC, wxy commented on contributions/20220529 Write a p2p Chat Program in Elixir.md
> +整个思路来源都是从这两个视频来的:<br>
这三行可以放在文末作为参考信息。而在此阐述你的这个应用的思路即可。可以更详细一点，因为下面就是具体的代码了，没有机会整体介绍架构了。

2022-06-18 08:37 UTC, wxy commented on contributions/20220529 Write a p2p Chat Program in Elixir.md
> +整个思路来源都是从这两个视频来的:<br>
整个设计思想和架构可以放一个段落。

2022-06-18 08:37 UTC, wxy commented on contributions/20220529 Write a p2p Chat Program in Elixir.md
> +整个思路来源都是从这两个视频来的:<br>
最好有个流程图/架构图。

2022-06-18 08:37 UTC, wxy commented on contributions/20220529 Write a p2p Chat Program in Elixir.md
> +- UDP 打洞<br>
关于版式，要注意几点：

- 空行分段
- 中英文间加空格
- 句末要有句号
- 代码段前后用空行和文字段分隔
- 避免大量代码，摘取必要段落，适当配以注释。

2022-06-18 08:37 UTC, wxy commented on contributions/20220529 Write a p2p Chat Program in Elixir.md
> +#### 服务端
应该先启动服务端？

2022-06-18 08:42 UTC, wxy commented
> 一个月前写的, 现在看来我写的太屑了

完全没有，很完整的一套思路。就是要介绍得更加深入浅出会更好。

其实类似的文章，比如国外的一些作者，就这个同样的主题，能写出一系列文章来，每篇就讲解其中一些主题部分。

这种文章，其实重点不在你将所有你认为的重要部分写给水平相当的人，而是要娓娓道来给不懂的读者，可以跟着你的步骤，一步步实现一个从未想过可以完成的项目。在这个过程中，学习到了语言、类库的特性，了解了某种系统的架构和可能的思考点。

文章，首先它不是个人笔记，而是“传道受业解惑”，你要从另外的人的角度来看，而不是，我只谈给知音听，听不懂算了。

以上是我个人的见解，仅供参考。

2022-06-18 08:54 UTC, dongdigua commented
好的, 谢谢你的这些建议, 我这就去改改, (这个最开始确实是从我个人笔记改过来的

2022-06-18 11:22 UTC, dongdigua commented
算了, 我NAT还没解决, 最近忙别的, 先不弄了吧

2022-06-18 11:22 UTC, closed without merging

2022-06-19 01:32 UTC, wxy commented
> 算了, 我NAT还没解决, 最近忙别的, 先不弄了吧

好吧，非常惋惜。等你有空时，建议整理出来给读者。