Contribute an article
LCTT/Articles pull request #31
Opened 2023-07-20 06:18 UTC by Chao-zhi

Bad writing, please correct me.

2023-07-26 05:03 UTC, wxy commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +在启用安全启动的 Fedora 中安装 Nvidia 驱动
Nvidia 在不是代码的地方，可以采用其官方的中文名称“英伟达”

2023-07-26 05:10 UTC, wxy requested changes
抱歉我一时给忘记了，赶快给你检查一下，望修改完善。

2023-07-26 05:10 UTC, wxy commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +现在新出厂的电脑 UEFI 会默认开启安全启动（Secure Boot），安全启动（secure boot）的作用是防止恶意软件侵入。当电脑引导器被病毒修改之后，它会给出提醒并拒绝启动，避免可能带来的进一步损失。不过它同样会阻止一些未经微软签名的 Linux 内核启动运行。虽然可以直接选择在主板设置中关闭安全启动来解决一系列麻烦，但就在近期微软公布的 Windows 11 最低硬件标准中可以看到
请适当使用 RUBY 标签做中英文参照。

2023-07-26 05:10 UTC, wxy commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +而最好用的发行版之一 Fedora 更热衷于开源驱动，其本身是支持安全启动的，但是当你通过 rpmfusion 安装官方的英伟达驱动，会造成这些驱动的内核模块未签名，Linux 启动过程中因为安全启动校验签名，会阻止加载这些模块，进而无法正常驱动显卡。用过 Ubuntu 的伙伴们应该知道，在安全启动开启的情况下 ，Ubuntu 安装程序会自动用自签密钥签名英伟达驱动内核模块，并在开机过程中自动将
这句话断句太长了，应该用短句，并在语义完整时用句号表结束。

2023-07-26 05:10 UTC, wxy commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +sudo kmodgenca -a
因为这种输出不常见，这个地方可以将输出作为示例给出，机密信息可以隐藏或删节。

2023-07-26 05:10 UTC, wxy commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +```sudo mokutil --import /etc/pki/akmods/certs/public_key.der```
这应该是个代码块

2023-07-26 05:10 UTC, wxy commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +重启后，你将看到蓝色的 MOK 管理器界面，不要惊惶，按照以下步骤注册密钥。
这个地方请给个 MOK 界面的截图。

2023-07-26 05:10 UTC, wxy commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +1. 首先选择 "Enroll MOK" 注册 MOK。
用中文的引号。

2023-07-26 05:10 UTC, wxy commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +#### 8. 确保启动 images 也已更新
images => 镜像

2023-07-26 05:10 UTC, wxy commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +``` shell
这样的示例输出就很有必要。

2023-07-26 09:17 UTC, Chao-zhi commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +在启用安全启动的 Fedora 中安装 Nvidia 驱动
已修改

2023-07-26 09:17 UTC, Chao-zhi commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +现在新出厂的电脑 UEFI 会默认开启安全启动（Secure Boot），安全启动（secure boot）的作用是防止恶意软件侵入。当电脑引导器被病毒修改之后，它会给出提醒并拒绝启动，避免可能带来的进一步损失。不过它同样会阻止一些未经微软签名的 Linux 内核启动运行。虽然可以直接选择在主板设置中关闭安全启动来解决一系列麻烦，但就在近期微软公布的 Windows 11 最低硬件标准中可以看到
已修改

2023-07-26 09:17 UTC, Chao-zhi commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +而最好用的发行版之一 Fedora 更热衷于开源驱动，其本身是支持安全启动的，但是当你通过 rpmfusion 安装官方的英伟达驱动，会造成这些驱动的内核模块未签名，Linux 启动过程中因为安全启动校验签名，会阻止加载这些模块，进而无法正常驱动显卡。用过 Ubuntu 的伙伴们应该知道，在安全启动开启的情况下 ，Ubuntu 安装程序会自动用自签密钥签名英伟达驱动内核模块，并在开机过程中自动将
已修改

2023-07-26 09:18 UTC, Chao-zhi commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +sudo kmodgenca -a
自己电脑不在手边，下个星期再复现一下再说

2023-07-26 09:18 UTC, Chao-zhi commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +```sudo mokutil --import /etc/pki/akmods/certs/public_key.der```
已修改

2023-07-26 09:18 UTC, Chao-zhi commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +1. 首先选择 "Enroll MOK" 注册 MOK。
已修改

2023-07-26 09:19 UTC, Chao-zhi commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +#### 8. 确保启动 images 也已更新
已修改

2023-07-31 14:18 UTC, Chao-zhi commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +sudo kmodgenca -a
该命令无输出

2023-07-31 14:18 UTC, Chao-zhi commented on contributions/20230720  Installing Nvidia Drivers in Secure Boot Enabled Fedora.md
> +重启后，你将看到蓝色的 MOK 管理器界面，不要惊惶，按照以下步骤注册密钥。
已添加截图

2023-08-05 10:31 UTC, wxy approved these changes

2023-08-05 10:31 UTC, merged