Create 商业 v. s. 自由 ——W*ndows v. s. 现代UNIX
LCTT/Articles pull request #7
Opened 2022-03-17 08:02 UTC by pengruiyang-cpu

上次的calvinlin佬是我好友，本人是个初一的小菜。
好久没用github了，平时一般用gitee多一点。

这篇文章可能有点**有意思**，希望通过吧……

2022-03-17 23:38 UTC, pengruiyang-cpu commented
好吧，自己的电脑被没收了，现在用的家里的win7，有些地方不太方便。周末我再改一下再pr

2022-03-18 02:51 UTC, wxy commented
非常棒，期待你的进一步完善。我稍后看看，如有建议，我写出来给你。

2022-03-18 03:26 UTC, wxy commented
有几点建议：

- 文件名请按要求使用，比如 `20220318 Linux vs Windows.md`
- 文章中我看到以 UNIX 对比 Windows，这里可能有点误区。最早期 UNIX 确实是自由的，但是后期其实一个商业产品及商标，而继承了 UNIX 自由精神的，是 *BSD 系列。至于 Linux，其实和 UNIX 没有血脉关系（SCO 诉 IBM 那个官司就是揪着这点，说 IBM 贡献了 UNIX 代码到 Linux 内核中）。本质上， Linux （和 BSD）继承了早期的黑客精神、UNIX 哲学、设计思路，但是完全不是 UNIX。所以，此处我建议你以 Linux 或 GNU/Linux 来做对比。
- 文章中大量使用了 `*` 来避免直接提及某些产品/商标/品牌以免带来侵权等麻烦，但是多了就容易造成阅读障碍。其实对于大部分情况下，直指名字是没问题的，有时候想行文上隐晦一些，可以用“某窗口”这样的形容。当然，可能这种 `*` 号用法是你们年轻人的习惯，不过，作为较为正式的发表文章，稍微正式一些比较好。（同样，“老比”我后面才看到你指的是盖茨。。这个比喻不太好，比如发音，以及不太常用。此处对盖茨先生没有不敬，我觉得可以用原名）
-  在行文衔接上，在第一个章节处有点问题，可以处理一下。
- 有关“邪教”这个段落，不要这样提，容易惹来不必要的问题。
- 最后，整体的文章脉络上，你还是要梳理一下，找出一个逻辑主线和中心思想（哈哈，有点像写作文了）

最后的最后，整体已经非常出乎我的预料，只能叹息后生可畏啊！期待进一步完善。

2022-03-19 06:32 UTC, pengruiyang-cpu commented
感谢，但是现在没法改这篇文章了（电脑还得等到晚上）;-(，等到拿到电脑我就马上改一改，内心还是挺激动的呢哈哈

2022-03-19 07:04 UTC, pengruiyang-cpu commented
现在用家里的Windows改了一下，应该差不多了。突然想起来如果要写名字的话，不要写pengruiyang-cpu，而是写intirain吧，谢谢！

2022-03-19 10:53 UTC, pengruiyang-cpu commented
commitmsg里头写错了，说明对象从unix到了linux

2022-03-19 14:50 UTC, wxy commented
这里，你大量使用了 ` 符号，不过我们的惯例是，一般只在 Linux 命令、文件名外用这个符号，其它地方大多用中文引号或不用。

2022-03-20 04:57 UTC, pengruiyang-cpu commented
ok, 我再改一下

2022-03-20 05:10 UTC, pengruiyang-cpu commented
根据《中文排版指北》改了改，中文、英文之间加了空格并且去掉了除了代码之外的几乎所有`。有问题请一定指出。

2022-03-22 01:00 UTC, wxy commented
> 根据《中文排版指北》改了改，中文、英文之间加了空格并且去掉了除了代码之外的几乎所有`。有问题请一定指出。

请查看我给出的行内审查，如果有不同意见，请给出。

2022-03-22 09:19 UTC, wxy requested changes

2022-03-22 09:19 UTC, wxy commented on contributions/20220319 Linux vs Windows.md
> +这一切的一切，都是因为某些公司……
此处和下面感觉意思上衔接不起来，可能是我没能理解你这里的转折。

2022-03-22 09:19 UTC, wxy commented on contributions/20220319 Linux vs Windows.md
> +再看看`Linux`世界怎么样？他支持全套的`POSIX`（`streams`除外），性能测试也不错（当然，窗口系统的裸机测试也不错。注意裸机），更令人骄傲的是优秀的进程创建以及文件系统。写“新文件系统”的那个程序员，大概是从同时代`IBM`的数据库计划挖过来的，一系列变长结构体直接把文件系统弄成了从头到尾的扫描磁盘性能，每次读取都可以称作是一次`fsck`。
“新文件系统”是什么？NTFS？另外，我没有听说过这个全盘扫描的操作——理论上这会慢的无法忍受。我觉得这里最好有个出处（链接）。另外上面的一些你提到的地方，比如“支持不多的几个系统调用”、“全套的 POSIX ”等，最好可以给出出处。

2022-03-22 09:19 UTC, wxy commented on contributions/20220319 Linux vs Windows.md
> +这一切的一切，都是因为某些公司……
或者，此处改成“这一切的一切，都是因为：”

2022-03-22 09:19 UTC, wxy commented on contributions/20220319 Linux vs Windows.md
> +对`UNIX`来说小菜一碟（弱弱问一句，`grep`有查看统计行数的功能吗）
这里这个括号里面的句子，破坏了整个文章的氛围，哈哈。建议删去。

2022-03-22 09:19 UTC, wxy commented on contributions/20220319 Linux vs Windows.md
> +如果你对文言文不是很熟悉，可以看译文：
这段译文可不要，回头我看看怎么润色一下。

2022-03-22 09:19 UTC, wxy commented on contributions/20220319 Linux vs Windows.md
> +理查德在演讲中说了的那样。
出处？

2022-03-22 09:19 UTC, wxy commented on contributions/20220319 Linux vs Windows.md
> +综上所述，那个商业系统就是被各种`daemon`以及糟糕的后台程序搅黄了，而它们总是喜欢位于后台的原因，根本上就是商业原因——看看你右下角那一个个小图标，它们应该比桌面上显眼吧！
daemon 指的是 UNIX/Linux 系统上的守护进程，在 Windows 上并不这样称呼，而是称之为“服务”。

2022-03-22 09:19 UTC, wxy commented on contributions/20220319 Linux vs Windows.md
> +也就是说，可怜的商业窗口系统，自己告别了原来属于自己的——无穷尽的自由软件开发人员。
我觉得，少个总结段落收束一下。

2022-03-22 09:23 UTC, pengruiyang-cpu commented on contributions/20220319 Linux vs Windows.md
> +再看看`Linux`世界怎么样？他支持全套的`POSIX`（`streams`除外），性能测试也不错（当然，窗口系统的裸机测试也不错。注意裸机），更令人骄傲的是优秀的进程创建以及文件系统。写“新文件系统”的那个程序员，大概是从同时代`IBM`的数据库计划挖过来的，一系列变长结构体直接把文件系统弄成了从头到尾的扫描磁盘性能，每次读取都可以称作是一次`fsck`。
确实有点引战了，我改的友好一点吧

2022-03-23 07:56 UTC, merged

2022-03-23 10:43 UTC, pengruiyang-cpu commented
链接实在不知道写啥了，另外我的地址还是写gitee的吧 https://gitee.com/intirain，因为github上是好久之前的东西了，怪丢人的（捂脸）另外图的话我在想，直接放个小企鹅、角牛和windows徽标咋样

2022-05-22 16:07 UTC, ghostflyby commented
# 事实性问题
## posix
Windows 上有 `_open` ，它就是 posix 风格的。事实上 Windows 上可以找到很多 posix 函数，只不过名称有前导`_`如`_write`，`_close`。
## 权限
企业和组织内会用到复杂的用户权限——它们用 Active Directory 集中管理。unix 权限终究不是为了控制一大堆机器的互相访问权限设计的。
# 个人见解
## 设计哲学
Windows 有 PowerShell 
```powershell
Get-Content foo |Select-String Windows |Measure-Object -Line
```
三个 Commandlet 分别用于获取文件内容（顺便一提`cat`是用来拼接文件的，只不过只拼接一个相当于获得内容）、在字符串里搜索、统计文件或字符串内容，我看也挺符合「设计哲学」的。


如果你认为 PowerShell 内置了一堆命令就不符合
> 每一个软件都平均不足 10 MB，并且都有着自己独特的分工。

大可以把内置命令当成大号 coreutils 和 findutils ,我看也没有谁 coreutils 只装一部分。

*顺便吐槽一下「独特的分工」，Linux 上也有`systemd`这样的「家伙」。*

## 「真幼稚」
开源和自由并不是一样的概念。

>启动最慢、内存占用最大的 Firefox 也只需要几秒钟时间，按一下鼠标就可以。对于那个系统，就应该不需要多说了吧……

经过我现场测试，我的 Windows 电脑上启动 Firefox 和 Edge 的时间都不超过 3 秒。

## 遣词
「某公司」、「某窗口系统」等表述大可不必。

PowerPoint not Power Point.
# 最后
说了这么多 unix 好，请问作者对 macOS 怎么看？
对商业公司发布的自由软件又怎么看？